#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include "auxFuncs.h"
#include "hasher.h"
#include "comparator.h"
#include "cmdstruct.h"
#include "nodes.h"
#include "doublelistcomp.h"
#include "hashtablecomp.h"
#include "hashtablecmd.h"
#include "cmdfuncexmpl.h"

