#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include "../../Includes/auxFuncs.h"
#include "../../Includes/nodes.h"
#include "../../Includes/comparator.h"
#include "../../Includes/hasher.h"
#include "doublelist.h"
#include "stackList.h"
#include "queueList.h"
#include "BST.h"
#include "../../Includes/doublelistcomp.h"
#include "../../Includes/hashtablecomp.h"
#include "minHeap.h"
