LDLIBS=-lSDL2 -lpthread -lm -L/home/hubbo/lib -Wl,-rpath,/home/hubbo/lib -Wl,--enable-new-dtags -lSDL2


INCLUDE=./Systems ./Types ./Factorized ./constantHeaders.
BINARY=ParticleSim
SOURCES=./Factorized ./resourcePaths  .  ./Systems  ./Types


CXX= g++
DEPFLAGS= -MP -MD

CXXFLAGS= -Wall -std=gnu++11 -Wextra -g $(foreach D, $(INCLUDE), -I$(D)) $(DEPFLAGS)

SOURCEFILES=$(foreach D,$(SOURCES), $(wildcard $(D)/*.cpp))

OBJECTS=$(patsubst %.cpp,%.o,$(SOURCEFILES))

DEPFILES= $(patsubst %.cpp,%.d,$(SOURCEFILES))


all: $(BINARY)
	echo $(LDLIBS)


$(BINARY): $(OBJECTS)
	$(CXX)  $(CXXFLAGS) -o $@ $^ $(LDLIBS)


%.o:%.c
	$(CXX)  $(CXXFLAGS) -c -o $@ $<  $(LDLIBS)  
	echo $(CXXFLAGS)
clean: 
	rm -rf $(BINARY) $(OBJECTS) $(DEPFILES)
