
ld -r -b binary -o resources/objects/file.o resources/embeded/file.txt
ld -r -b binary -o resources/objects/file2.o resources/embeded/file2.txt
ld -r -b binary -o resources/objects/file3.o resources/embeded/file3.txt
ld -r -b binary -o resources/objects/password.o resources/embeded/password
ld -r -b binary -o resources/objects/musica.o resources/embeded/musica
ld -r -b binary -o resources/objects/musica2.o resources/embeded/musica2
ld -r -b binary -o resources/objects/musica3.o resources/embeded/musica3
ld -r -b binary -o resources/objects/splash.o resources/embeded/splash
ld -r -b binary -o resources/objects/img1.o resources/embeded/img1
ld -r -b binary -o resources/objects/img2.o resources/embeded/img2
ld -r -b binary -o resources/objects/img3.o resources/embeded/img3
ld -r -b binary -o resources/objects/img4.o resources/embeded/img4
ld -r -b binary -o resources/objects/img5.o resources/embeded/img5
ld -r -b binary -o resources/objects/img6.o resources/embeded/img6
ld -r -b binary -o resources/objects/img7.o resources/embeded/img7
ld -r -b binary -o resources/objects/img8.o resources/embeded/img8
ld -r -b binary -o resources/objects/img9.o resources/embeded/img9
ld -r -b binary -o resources/objects/img10.o resources/embeded/img10
ld -r -b binary -o resources/objects/img11.o resources/embeded/img11
ld -r -b binary -o resources/objects/kissing.o resources/embeded/kissing
ld -r -b binary -o resources/objects/kissing2.o resources/embeded/kissing2
