#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include "auxFuncs.h"
#include "nodes.h"
#include "comparator.h"
#include "doublelist.h"
#include "doublelistcomp.h"
#include "stackList.h"
#include "queueList.h"
#include "BST.h"
#include "hashtable.h"
#include "hashtablecomp.h"
#include "minHeap.h"
