#ifndef BULLETCONSTS_H
#define BULLETCONSTS_H

#define DEFAULTBULLETRGBA ((SDL_Color){0,0,0,255})
#define DEFAULTBULLETSIZE 10
#define DEFAULTBULLETE 1
#define DEFAULTBULLETM 10
#define DEFAULTBULLETCAR 100
#define DEFAULTBULLETQ 10

#endif

