#ifndef COLSETTINGS_H
#define COLSETTINGS_H

#define DEFAULTCOLX 0
#define DEFAULTCOLY 0
#define DEFAULTCOLRGB ((SDL_Color){255,255,255,255})
#define DEFAULTCOLH 800
#define DEFAULTCOLW 600
#define DEFAULTAIRDENSITY 1
#define DEFAULTTHICKNESS 500

#endif
