#ifndef ENT_SET_H
#define ENT_SET_H

#define DEFAULTENTMAXX WIDTH
#define DEFAULTENTMAXY HEIGHT
#define DEFAULTENTMAXMASS 100
#define DEFAULTENTMAXCHARGE 100
#define DEFAULTENTMAXSIZE 100
#define DEFAULTENTMAXSPEED 2



#endif
