#ifndef G_SETTINGS_H
#define G_SETTINGS_H

#define DEFAULTGRENADERGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGRENADESIZE 10
#define DEFAULTGRENADEE 0.3
#define DEFAULTGRENADEM 1
#define DEFAULTGRENADEQ 1
#define DEFAULTGRENADECAR 1
#define DEFAULTGRENADEBFORCE 25000000
#define DEFAULTGRENADETIMER 25
#define DEFAULTEXPLOSIONDUR 3


#endif
