#ifndef GUNCONSTS_H
#define GUNCONSTS_H

#define DEFAULTGUNRGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGUNW 50
#define DEFAULTGUNH 50
#define DEFAULTGUNE 1
#define DEFAULTGUNM 10
#define DEFAULTGUNQ 10
#define DEFAULTGUNCAR 1
#define DEFAULTGUNFORCE 1
#define DEFAULTGUNRECOIL 1
#define DEFAULTGUNBARRELLENGTH 5
#define DEFAULTGUNSPREAD 0
#define DEFAULTGUNCAP 30
#define DEFAULTGUNRELTIME 1
#define DEFAULTGUNSHOTTIME 60



#define DEFAULTGLAUNCHERRGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGLAUNCHERW 50
#define DEFAULTGLAUNCHERH 50
#define DEFAULTGLAUNCHERE 1
#define DEFAULTGLAUNCHERM 10
#define DEFAULTGLAUNCHERQ 10
#define DEFAULTGLAUNCHERCAR 1
#define DEFAULTGLAUNCHERFORCE 10
#define DEFAULTGLAUNCHERRECOIL 1
#define DEFAULTGLAUNCHERBARRELLENGTH 10
#define DEFAULTGLAUNCHERSPREAD 0
#define DEFAULTGLAUNCHERCAP 30
#define DEFAULTGLAUNCHERRELTIME 100
#define DEFAULTGLAUNCHERSHOTTIME 10

#define DEFAULTMLAUNCHERRGBA ((SDL_Color){255,0,0,255})
#define DEFAULTMLAUNCHERW 50
#define DEFAULTMLAUNCHERH 50
#define DEFAULTMLAUNCHERE 1
#define DEFAULTMLAUNCHERM 10
#define DEFAULTMLAUNCHERQ 10
#define DEFAULTMLAUNCHERCAR 1
#define DEFAULTMLAUNCHERFORCE 10
#define DEFAULTMLAUNCHERRECOIL 1
#define DEFAULTMLAUNCHERBARRELLENGTH 10
#define DEFAULTMLAUNCHERSPREAD 0
#define DEFAULTMLAUNCHERCAP 30
#define DEFAULTMLAUNCHERRELTIME 100
#define DEFAULTMLAUNCHERSHOTTIME 10


#endif
