#ifndef MISSILE_SET_H
#define MISSILE_SET_H



#define DEFAULTMISSILERGBA ((SDL_Color){0,255,0,255})
#define DEFAULTMISSILESIZE 10
#define DEFAULTMISSILEE 0.3
#define DEFAULTMISSILEM 1
#define DEFAULTMISSILEQ 1
#define DEFAULTMISSILECAR 1
#define DEFAULTMISSILEBFORCE 25000000
#define DEFAULTMISSILETIMER 180
#define DEFAULTMISSILERANGE 10000
#define DEFAULTMISSILESPEED 7


#endif

