#ifndef BULLETCONSTS_H
#define BULLETCONSTS_H

#define DEFAULTBULLETRGBA ((SDL_Color){0,0,0,255})
#define DEFAULTBULLETSIZE 100
#define DEFAULTBULLETE 1
#define DEFAULTBULLETM 100000000
#define DEFAULTBULLETCAR 100

#endif

