#ifndef G_SETTINGS_H
#define G_SETTINGS_H

#define DEFAULTGRENADERGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGRENADESIZE 10
#define DEFAULTGRENADEE 1
#define DEFAULTGRENADEM 10
#define DEFAULTGRENADECAR 100
#define DEFAULTGRENADEBFORCE 1000000
#define DEFAULTGRENADETIMER 100
#define DEFAULTEXPLOSIONDUR 1000


#endif
