#ifndef G_SETTINGS_H
#define G_SETTINGS_H

#define DEFAULTGRENADERGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGRENADESIZE 10
#define DEFAULTGRENADEE 0.3
#define DEFAULTGRENADEM 1
#define DEFAULTGRENADECAR 0
#define DEFAULTGRENADEBFORCE 10000000
#define DEFAULTGRENADETIMER 100
#define DEFAULTEXPLOSIONDUR 30


#endif
