#ifndef GUNCONSTS_H
#define GUNCONSTS_H

#define DEFAULTGUNRGBA ((SDL_Color){0,0,0,255})
#define DEFAULTGUNW 100
#define DEFAULTGUNH 100
#define DEFAULTGUNE 1
#define DEFAULTGUNM 10
#define DEFAULTGUNCAR 1
#define DEFAULTGUNFORCE 1
#define DEFAULTGUNRECOIL 1
#define DEFAULTGUNBARRELLENGTH 5
#define DEFAULTGUNSPREAD 0
#define DEFAULTGUNCAP 30
#define DEFAULTGUNRELTIME 1
#define DEFAULTGUNSHOTTIME 60

#endif
